name = "zuohe-points-api"
main = "src/index.ts"
compatibility_date = "2024-12-01"
account_id = "7183938e807f105a7e7628693729280b"

[vars]
JWT_SECRET = "zuohe-points-secret-key-change-in-production"

[[d1_databases]]
binding = "DB"
database_name = "zuohe-points-db"
database_id = "013c4e41-fc00-4fe0-95d0-b301bd1c8d66"
