name = "zuohe-points-api"
main = "src/index.ts"
compatibility_date = "2024-12-01"
account_id = "a07875812cf0f78a5d637060a5a7956b"

[vars]
JWT_SECRET = "zuohe-points-secret-key-change-in-production"

[[d1_databases]]
binding = "DB"
database_name = "zuohe-points-db"
database_id = "4b4ce129-6e96-4642-b5fb-f303cdebeca0"
